// Status updates for V2-CHECKLIST.md. Keys are row IDs; values are
// [Done, Tested, Evidence]. Requirement wording is never changed.
export const MARKS = {
  "P0-01": ["☑ Done", "☑ Tested", "Both files exist in root"],
  "P0-02": ["☑ Done", "☑ Tested", "Search for `[ &A-Z]` across `assets/images` returns nothing"],
  "P0-03": ["☑ Done", "☑ Tested", "MD5 all matched `1D17A88A…`; merged to `assets/images/logo/logo-white-mark.png`"],
  "P0-04": ["☑ Done", "☑ Tested", "`tools/verify.mjs`: 219 local refs, 0 broken"],
  "P0-05": ["☑ Done", "☑ Tested", "Repo-wide search for every old filename returns 0 hits"],

  "NAV-01": ["≈ Q7", "☑ Tested", "Used `logo/logo-blue-mark.png` (trimmed of empty border). Visible on all 11 pages"],
  "NAV-02": ["≈ Q18", "☑ Tested", "`navbar-nav mx-auto` — links sit between logo and Contact button"],
  "NAV-03": ["≈ Q18", "☑ Tested", "Nav links use `--royal` (#1e5aa8); Contact button keeps primary brand navy"],
  "NAV-04": ["☑ Done", "☑ Tested", "0 hits for `data-nav=\"home\"` across all pages"],

  "HOME-01": ["≈ Q3", "☑ Tested", "Hero copy now reads \"across England.\""],
  "HOME-02": ["≈ Q26", "☑ Tested", "Items 1–3 link to their pages; item 4 anchors to `#our-services`"],
  "HOME-03": ["☑ Done", "☑ Tested", "Hover scale 1.08 confirmed in Playwright"],
  "HOME-04": ["≈ Q32", "☑ Tested", "Wrapped in `.panel-box` (18px radius, soft shadow)"],
  "HOME-05": ["☑ Done", "☑ Tested", "Line removed; remaining two paragraphs confirmed"],
  "HOME-06": ["≈ Q19", "☑ Tested", "Both buttons upgraded to `btn-lg px-5 py-3`"],
  "HOME-07": ["≈ Q20", "☑ Tested", "Two-column Why Us list + Projects We Support chips"],
  "HOME-08": ["≈ Q20", "☑ Tested", "8 Why Us items + 10 Projects We Support chips match the template"],
  "HOME-09": ["☑ Done", "☑ Tested", "Hover bg → `#F4F8FF` confirmed"],
  "HOME-10": ["☑ Done", "☑ Tested", "Hover shadow + 2px lift confirmed"],
  "HOME-11": ["☑ Done", "☑ Tested", "`var(--transition)` 0.25s ease applied"],
  "HOME-12": ["☑ Done", "☑ Tested", "Chip hover darkens to `#dbe7f8`"],
  "HOME-13": ["☑ Done", "☑ Tested", "Chip hover shadow + 3px lift confirmed"],
  "HOME-14": ["☑ Done", "☑ Tested", "`var(--transition)` applied"],
  "HOME-15": ["☑ Done", "☑ Tested", "5 `.process-box` cards"],
  "HOME-16": ["≈ Q32", "☑ Tested", "`var(--shadow-soft)` applied"],
  "HOME-17": ["≈ Q32", "☑ Tested", "`--radius-box: 18px`"],
  "HOME-18": ["☑ Done", "☑ Tested", "6px lift + stronger shadow confirmed"],
  "HOME-19": ["☑ Done", "☑ Tested", "3px royal top border confirmed"],
  "HOME-20": ["☑ Done", "☑ Tested", "numOpacity→0, logoOpacity→1 on hover confirmed"],
  "HOME-21": ["☑ Done", "☑ Tested", "Heading reads \"Consultation\""],
  "HOME-22": ["☑ Done", "☑ Tested", "Heading reads \"Site & Project Review\""],
  "HOME-23": ["☑ Done", "☑ Tested", "Heading reads \"Planning Approval\""],
  "HOME-24": ["☑ Done", "☑ Tested", "Border → navy on hover confirmed"],
  "HOME-25": ["☑ Done", "☑ Tested", "Background → `rgb(244, 248, 255)` confirmed"],
  "HOME-26": ["☑ Done", "☑ Tested", "5px lift confirmed"],
  "HOME-27": ["☑ Done", "☑ Tested", "Icon scale 1.18 confirmed"],
  "HOME-28": ["☑ Done", "☑ Tested", "Estate Agents present; Commercial Property Owners gone"],
  "HOME-29": ["≈ Q27", "☑ Tested", "Bootstrap Icons on all 5 cards"],
  "HOME-30": ["☑ Done", "☑ Tested", "0 hits for \"Investors\" on index"],
  "HOME-31": ["☑ Done", "☑ Tested", "0 hits for `reviews-placeholder`"],
  "HOME-32": ["☑ Done", "☑ Tested", "`.achievement-grid` with 4 cards"],
  "HOME-33": ["☑ Done", "☑ Tested", "\"5+\" card present"],
  "HOME-34": ["≈ Q22", "☑ Tested", "Built as \"1K+\" pending client confirmation"],
  "HOME-35": ["☑ Done", "☑ Tested", "\"England\" card present"],
  "HOME-36": ["☑ Done", "☑ Tested", "\"Residential & Commercial\" card present"],
  "HOME-37": ["☑ Done", "☑ Tested", "Eyebrow under the main heading"],

  "FOOT-01": ["☑ Done", "☑ Tested", "`mailto:` present on all 11 pages"],
  "FOOT-02": ["≈ Q1", "☑ Tested", "`tel:` + `wa.me` wired with placeholder `+44 XX XXXX XXXX` until the real number arrives"],
  "FOOT-03": ["≈ Q6", "☑ Tested", "Fixed year 2026 + legalese on the bottom bar of all 11 pages"],
  "FOOT-04": ["≈ Q4", "☑ Tested", "Registration line removed from the brand column; kept only on the bottom bar"],

  "LEG-01": ["☑ Done", "☑ Tested", "Supplied five-section copy live on `terms.html`"],
  "LEG-02": ["☑ Done", "☑ Tested", "Supplied six-section copy live on `privacy.html`"],
  "LEG-03": ["≈ Q5", "☑ Tested", "Shipped as its own page `cookies.html` (linked from every footer)"],
  "LEG-04": ["☑ Done", "☑ Tested", "0 hits for \"placeholder policy\""],

  "ABT-01": ["☑ Done", "☑ Tested", "\"WHO WE ARE\" eyebrow above the main heading"],
  "ABT-02": ["☑ Done", "☑ Tested", "Supplied hero paragraph live"],
  "ABT-03": ["☑ Done", "☑ Tested", "`about/hero-banner.png` resolves"],
  "ABT-04": ["☑ Done", "☑ Tested", "Who We Are section gone; Mission is first content section"],
  "ABT-05": ["☑ Done", "☑ Tested", "`.mission-panel` with `our-mission.png`"],
  "ABT-06": ["☑ Done", "☑ Tested", "Both headings present"],
  "ABT-07": ["☑ Done", "☑ Tested", "White text confirmed in screenshot"],
  "ABT-08": ["☑ Done", "☑ Tested", "0 hits for Industries We Serve on about"],
  "ABT-09": ["≈ Q21", "☑ Tested", "Built as 5 zigzag rows (brief lists 5; template's 6th unused)"],
  "ABT-10": ["≈ Q21", "☑ Tested", "Row A: text then Consultation image"],
  "ABT-11": ["≈ Q21", "☑ Tested", "Row B: Site & Project Review image then text"],
  "ABT-12": ["≈ Q21", "☑ Tested", "Row C: text then Design & Engineering image"],
  "ABT-13": ["≈ Q21", "☑ Tested", "Row D: Planning Approval image then text"],
  "ABT-14": ["≈ Q21", "☑ Tested", "Row E: text then Project Delivery image"],
  "ABT-15": ["☑ Done", "☑ Tested", "Why Choose Us section removed"],
  "ABT-16": ["☑ Done", "☑ Tested", "`.expertise-panel` present"],
  "ABT-17": ["≈ Q8", "☑ Tested", "`about/expertise-bg.png` used as the panel head"],
  "ABT-18": ["☑ Done", "☑ Tested", "\"OUR EXPERTISE\" eyebrow in light blue"],
  "ABT-19": ["☑ Done", "☑ Tested", "Supplied subheading present"],
  "ABT-20": ["≈ Q15", "☑ Tested", "7 tiles with the 7 supplied icons (brief lists 7)"],
  "ABT-21": ["☑ Done", "☑ Tested", "Tile hover scale 1.07 + lift"],
  "ABT-22": ["≈ Q15", "☑ Tested", "Grid of icon tiles under a photo header, matching the template"],
  "ABT-23": ["☑ Done", "☑ Tested", "6 accordion items"],
  "ABT-24": ["☑ Done", "☑ Tested", "Section + heading + intro present"],
  "ABT-25": ["≈ Q23", "☑ Tested", "About form keeps its own lighter field set as supplied"],
  "ABT-26": ["☑ Done", "☑ Tested", "6 service options in the dropdown"],
  "ABT-27": ["☑ Done", "☑ Tested", "Project Details textarea required"],
  "ABT-28": ["≈ Q2", "☑ Tested", "File input present; helper text asks user to attach in the mail client (mailto cannot carry files)"],
  "ABT-29": ["☑ Done", "☑ Tested", "Phone / Email / WhatsApp radios present"],
  "ABT-30": ["☑ Done", "☑ Tested", "Button labelled \"Request Your Free Quote\""],
  "ABT-31": ["≈ Q2", "☑ Tested", "Mailto handoff verified in Playwright with all fields in the body"],
  "ABT-32": ["≈ Q1", "☑ Tested", "Phone + WhatsApp in the shared footer (placeholder number)"],
  "ABT-33": ["☑ Done", "☑ Tested", "0 hits for \"Ready to Work With Us\""],
  "ABT-34": ["☑ Done", "☑ Tested", "Company details block below CTA removed"],
  "ABT-35": ["≈ Q24", "N/A", "No Privacy section exists on this page — nothing to leave"],

  "ARCH-01": ["≈ Q25", "☑ Tested", "Nav/title/footer say \"Architectural Design\"; file path kept as `architectural.html`"],
  "ARCH-02": ["≈ Q3", "☑ Tested", "Heading no longer contains \"Across England & Wales\""],
  "ARCH-03": ["☑ Done", "☑ Tested", "Eyebrow reads \"Architectural Services\""],
  "ARCH-04": ["≈ Q12", "☑ Tested", "Lighter overlay via `.page-hero--showcase`"],
  "ARCH-05": ["≈ Q29", "☑ Tested", "Ticker: seamless 42s loop, pauses on hover"],
  "ARCH-06": ["☑ Done", "☑ Tested", "bg `rgb(30,90,168)`, text white"],
  "ARCH-07": ["☑ Done", "☑ Tested", "`.section-title--lg` in royal blue"],
  "ARCH-08": ["☑ Done", "☑ Tested", "`.service-block:hover` lift + light-blue fill"],
  "ARCH-09": ["☑ Done", "☑ Tested", "`planning-drawings.png` resolves"],
  "ARCH-10": ["☑ Done", "☑ Tested", "`extension.png` replaced the placeholder"],
  "ARCH-11": ["☑ Done", "☑ Tested", "`garage-conversions.png` resolves"],
  "ARCH-12": ["☑ Done", "☑ Tested", "`new-build.png` resolves"],
  "ARCH-13": ["☑ Done", "☑ Tested", "`internal-alterations.png` resolves"],
  "ARCH-14": ["≈ Q14", "☑ Tested", "Kept both unlisted cards (Building Regs + Loft) since they already had images"],
  "ARCH-15": ["☑ Done", "☑ Tested", "`.why-box` on each reason"],
  "ARCH-16": ["☑ Done", "☑ Tested", "Hover invert to blue/white"],
  "ARCH-17": ["☑ Done", "☑ Tested", "5 process boxes"],
  "ARCH-18": ["☑ Done", "☑ Tested", "Logo swap confirmed in Playwright screenshot"],
  "ARCH-19": ["≈ Q30", "☑ Tested", "Hover reveals photo + scales to 1.07; Concept Design hover screenshot captured"],
  "ARCH-20": ["☑ Done", "☑ Tested", "`consultation.png`"],
  "ARCH-21": ["☑ Done", "☑ Tested", "`on-site.png`"],
  "ARCH-22": ["☑ Done", "☑ Tested", "`concept-design.png`"],
  "ARCH-23": ["☑ Done", "☑ Tested", "`drawings.png`"],
  "ARCH-24": ["☑ Done", "☑ Tested", "`delivery.png`"],
  "ARCH-25": ["☑ Done", "☑ Tested", "`.benefits-panel--light` with `benefits-bg.png`"],
  "ARCH-26": ["☑ Done", "☑ Tested", "Heading in royal blue"],
  "ARCH-27": ["☑ Done", "☑ Tested", "Supplied description on the right"],
  "ARCH-28": ["≈ Q27", "☑ Tested", "6 benefit items with Bootstrap Icons"],
  "ARCH-29": ["≈ Q28", "☑ Tested", "Tick circle + icon on every benefit"],
  "ARCH-30": ["☑ Done", "☑ Tested", "FAQ section unchanged"],

  "STR-01": ["≈ Q3", "☑ Tested", "Heading no longer contains \"Across England & Wales\""],
  "STR-02": ["≈ Q11", "☑ Tested", "Uses existing `structural/hero-bg.png` (already on the page)"],
  "STR-03": ["☑ Done", "☑ Tested", "Supplied paragraph live"],
  "STR-04": ["≈ Q29", "☑ Tested", "Ticker present"],
  "STR-05": ["☑ Done", "☑ Tested", "Blue bg / white text"],
  "STR-06": ["☑ Done", "☑ Tested", "`.section-title--lg`"],
  "STR-07": ["☑ Done", "☑ Tested", "`.service-block:hover`"],
  "STR-08": ["≈ Q13", "☑ Tested", "Used `str-calcs.png` for the Calculations card"],
  "STR-09": ["≈ Q13", "☑ Tested", "Uses new `rsj.png`"],
  "STR-10": ["≈ Q13", "☑ Tested", "Uses new `reports.png`"],
  "STR-11": ["≈ Q13", "☑ Tested", "Uses new `foundations.png`"],
  "STR-12": ["≈ Q13", "☑ Tested", "Uses new `retaining.png`"],
  "STR-13": ["≈ Q13", "☑ Tested", "Uses new `roof.png`"],
  "STR-14": ["☑ Done", "☑ Tested", "`.why-box`"],
  "STR-15": ["☑ Done", "☑ Tested", "Hover invert"],
  "STR-16": ["☑ Done", "☑ Tested", "5 process boxes"],
  "STR-17": ["☑ Done", "☑ Tested", "Logo swap"],
  "STR-18": ["≈ Q30", "☑ Tested", "Hover photo + scale"],
  "STR-19": ["☑ Done", "☑ Tested", "`ini-cons.png`"],
  "STR-20": ["☑ Done", "☑ Tested", "`str-asses.png`"],
  "STR-21": ["☑ Done", "☑ Tested", "`str-desi.png`"],
  "STR-22": ["≈ Q13", "☑ Tested", "`calcs.png` used for the process hover"],
  "STR-23": ["☑ Done", "☑ Tested", "`cons.png`"],
  "STR-24": ["☑ Done", "☑ Tested", "`.benefits-panel--dark`"],
  "STR-25": ["☑ Done", "☑ Tested", "Heading white"],
  "STR-26": ["☑ Done", "☑ Tested", "Supplied description"],
  "STR-27": ["≈ Q27", "☑ Tested", "6 benefit items with icons"],
  "STR-28": ["≈ Q28", "☑ Tested", "Tick + icon"],
  "STR-29": ["☑ Done", "☑ Tested", "FAQ unchanged"],
  "STR-30": ["≈ Q4", "☑ Tested", "Registration line removed from brand column sitewide"],

  "PW-01": ["≈ Q3", "☑ Tested", "Heading no longer contains \"Across England\""],
  "PW-02": ["☑ Done", "☑ Tested", "`partywall/hero-banner.png` replaces the gradient"],
  "PW-03": ["☑ Done", "☑ Tested", "Supplied paragraph live"],
  "PW-04": ["≈ Q29", "☑ Tested", "Ticker: 42s loop, pauses on hover"],
  "PW-05": ["☑ Done", "☑ Tested", "Blue bg / white text"],
  "PW-06": ["☑ Done", "☑ Tested", "`.service-item` light card styling"],
  "PW-07": ["☑ Done", "☑ Tested", "Hover darkens `#f0f4f8` → `#e0e7ef`, lifts 2px"],
  "PW-08": ["☑ Done", "☑ Tested", "4 process boxes"],
  "PW-09": ["☑ Done", "☑ Tested", "Logo swap"],
  "PW-10": ["☑ Done", "☑ Tested", "`.process-box--blue`"],
  "PW-11": ["≈ Q30", "☑ Tested", "Hover photo + scale"],
  "PW-12": ["≈ Q9", "☑ Tested", "`inti-vis.jpg` used"],
  "PW-13": ["☑ Done", "☑ Tested", "`asses.png`"],
  "PW-14": ["☑ Done", "☑ Tested", "`docu.png`"],
  "PW-15": ["☑ Done", "☑ Tested", "`ongi.png`"],
  "PW-16": ["☑ Done", "☑ Tested", "`.benefits-panel--dark`"],
  "PW-17": ["☑ Done", "☑ Tested", "Supplied description"],
  "PW-18": ["≈ Q27", "☑ Tested", "6 benefit items"],
  "PW-19": ["≈ Q28", "☑ Tested", "Tick + icon"],
  "PW-20": ["☑ Done", "☑ Tested", "FAQ unchanged"],
  "PW-21": ["≈ Q4", "☑ Tested", "Registration line removed from brand column sitewide"],

  "SUR-01": ["≈ Q3", "☑ Tested", "Heading no longer contains \"Across England & Wales\""],
  "SUR-02": ["≈ Q10", "☑ Tested", "Kept the existing `surveys/hero-bg.png` (brief named a file that wasn't supplied)"],
  "SUR-03": ["≈ Q29", "☑ Tested", "Ticker present"],
  "SUR-04": ["☑ Done", "☑ Tested", "Blue bg / white text"],
  "SUR-05": ["☑ Done", "☑ Tested", "`.section-title--lg`"],
  "SUR-06": ["☑ Done", "☑ Tested", "`.service-block:hover`"],
  "SUR-07": ["☑ Done", "☑ Tested", "`cracks.png`"],
  "SUR-08": ["☑ Done", "☑ Tested", "`inspection.png`"],
  "SUR-09": ["☑ Done", "☑ Tested", "`pre-purchase.png`"],
  "SUR-10": ["☑ Done", "☑ Tested", "`snagging.png`"],
  "SUR-11": ["☑ Done", "☑ Tested", "`.why-box`"],
  "SUR-12": ["☑ Done", "☑ Tested", "Hover invert"],
  "SUR-13": ["☑ Done", "☑ Tested", "5 process boxes"],
  "SUR-14": ["☑ Done", "☑ Tested", "Logo swap"],
  "SUR-15": ["☑ Done", "☑ Tested", "`.process-box--blue`"],
  "SUR-16": ["≈ Q31", "☑ Tested", "No hover backgrounds applied (none were supplied); logo-swap hover still works"],
  "SUR-17": ["☑ Done", "☑ Tested", "`.benefits-panel--dark`"],
  "SUR-18": ["☑ Done", "☑ Tested", "Supplied description"],
  "SUR-19": ["≈ Q27", "☑ Tested", "6 benefit items"],
  "SUR-20": ["≈ Q28", "☑ Tested", "Tick + icon"],
  "SUR-21": ["☑ Done", "☑ Tested", "FAQ unchanged"],
  "SUR-22": ["≈ Q4", "☑ Tested", "Registration line removed from brand column sitewide"],

  "PLN-01": ["≈ Q3", "☑ Tested", "Heading no longer contains \"Across England & Wales\""],
  "PLN-02": ["☑ Done", "☑ Tested", "`planning/hero-bg.png` already on the page"],
  "PLN-03": ["≈ Q29", "☑ Tested", "Ticker present"],
  "PLN-04": ["☑ Done", "☑ Tested", "Blue bg / white text"],
  "PLN-05": ["☑ Done", "☑ Tested", "`.icon-service--card` hover lift"],
  "PLN-06": ["☑ Done", "☑ Tested", "Icon opacity→0, logo opacity→1, wrap bg→royal confirmed"],
  "PLN-07": ["☑ Done", "☑ Tested", "Headings in royal blue"],
  "PLN-08": ["☑ Done", "☑ Tested", "4 process boxes"],
  "PLN-09": ["☑ Done", "☑ Tested", "Logo swap"],
  "PLN-10": ["☑ Done", "☑ Tested", "`.process-box--blue`"],
  "PLN-11": ["≈ Q31", "☑ Tested", "No hover backgrounds applied (none were supplied)"],
  "PLN-12": ["N/A", "N/A", "Confirmed: this page has no FAQ section"],
  "PLN-13": ["≈ Q4", "☑ Tested", "Registration line removed from brand column sitewide"],

  "CON-01": ["☑ Done", "☑ Tested", "White-with-name logo on the left of the hero"],
  "CON-02": ["☑ Done", "☑ Tested", "Heading in navy"],
  "CON-03": ["☑ Done", "☑ Tested", "`.contact-panel` matches the specified shadow/radius/padding"],
  "CON-04": ["☑ Done", "☑ Tested", "5% opacity grid via `::before`"],
  "CON-05": ["☑ Done", "☑ Tested", "4px royal-bright accent via `::after`"],
  "CON-06": ["☑ Done", "☑ Tested", "4 contact cards"],
  "CON-07": ["☑ Done", "☑ Tested", "White / 16px / `#E8EDF4` / soft shadow"],
  "CON-08": ["☑ Done", "☑ Tested", "5px lift + stronger shadow on hover"],
  "CON-09": ["☑ Done", "☑ Tested", "56×56 `#EEF5FF` / `#0057D9`"],
  "CON-10": ["☑ Done", "☑ Tested", "Uppercase label + larger value"],
  "CON-11": ["☑ Done", "☑ Tested", "Icon invert + blue border on hover"],
  "CON-12": ["☑ Done", "☑ Tested", "Supplied paragraph live"],
  "CON-13": ["☑ Done", "☑ Tested", "Mon–Fri / Sat / Sun with day/time columns"],
  "CON-14": ["☑ Done", "☑ Tested", "Heading in navy"],
  "CON-15": ["☑ Done", "☑ Tested", "0 hits for `areas-text`"],
  "CON-16": ["≈ Q4", "☑ Tested", "Registration line removed from brand column sitewide"],

  "VER-01": ["☑ Done", "☑ Tested", "Full-page screenshots of home / about / contact / architectural captured via Playwright"],
  "VER-02": ["☑ Done", "☑ Tested", "Overflow sweep at 360/390/576/768/992/1200/1440/1920 — all 11 pages ok"],
  "VER-03": ["☑ Done", "☑ Tested", "Industry / why-list / chip / process / hero-link / planning-icon / service-item hovers measured"],
  "VER-04": ["☑ Done", "☑ Tested", "`tools/verify.mjs`: 0 broken internal links"],
  "VER-05": ["☑ Done", "☑ Tested", "`tools/verify.mjs` + Playwright image check: 0 broken images"],
  "VER-06": ["☑ Done", "☑ Tested", "Applied via `tools/apply-shell.mjs`; identical markup on all 11 pages"],
  "VER-07": ["≈ Q1", "☐", "Placeholders remain until the client supplies the real number"],
  "VER-08": ["☐", "☐", "Awaiting client answers in `V2-QUESTIONS.md` — every assumption is marked `≈ Qn` above"],

  "BUG-01": ["☑ Done", "☑ Tested", "Replaced `bi-handshake` with `bi-people`"],
  "BUG-02": ["☑ Done", "☑ Tested", "Replaced `bi-balance-scale` with `bi-clipboard-check`"],
  "BUG-03": ["≈ Q17", "☑ Tested", "Favicon set to `logo/logo-blue-mark.png` on all 11 pages"],
  "BUG-04": ["☑ Done", "☑ Tested", "Shared shell now includes `data-nav` on every page"],
  "BUG-05": ["☐", "☐", "Left alone — not in the brief; flagging only"],
};
